= Simple Values
:source-highlighter: coderay
:source-language: clojure
:sectnums:
:icons: font
:imagesdir: ../img
:stylesdir: ../
:stylesheet: my-asciidoctor.css

== Clojure Data Type Diagram

다음의 도표는 클로저의 모든 자료형들을 한 눈에 살펴볼 수 있도록 일목요연하게 정리한
것이다. 먼저 전체적인 지도를 마음 속에 두고 각 부분을 자세하게 살펴 나가는 것이 클로저를
빠르고 정확하게 이해하는 지름길이다. 각 자료형 옆에는 실제로 구현되어 있는 자바 클래스를
병기했다. 이 장에서는 단순 자료형(Simple values)들을 중심으로 살펴보고, 다음 장에서 복합
자료형인 Collection들을 살펴 보겠다.

[[clojure-data-type-diagram]]


[cols="1,1,^.^2,^.^6", width="70%", options="header"]
|===
|  |  ^| 클로저 타입 ^| 자바 클래스

.13+^.^v|Immutables
(= Values)

.9+^.^|Simple values
^.^| Integers
^v| java.lang.Long
clojure.lang.BigInt

^.^| Floats
^v| java.lang.Double +
java.math.BigDecimal

^.^| Ratios     ^| clojure.lang.Ratio

^.^| Strings    ^| java.lang.String

^.^| Characters ^| java.lang.Character

^.^| Symbols    ^| clojure.lang.Symbol

^.^| Keywords   ^| clojure.lang.Keyword

^.^| Booleans   ^| java.lang.Boolean

^| nil          ^| null


.4+^.^|Collections
^| Lists         | clojure.lang.PersistentList

^| Vectors      ^| clojure.lang.PersistentVector

^.^| Maps
^v| array-map: clojure.lang.PersistentArrayMap
hash-map: clojure.lang.PersistentHashMap
sorted-map: clojure.lang.PersistentTreeMap

^.^| Sets
^v| hash-set: clojure.lang.PersistentHashSet
sorted-set: clojure.lang.PersistentTreeSet

.4+^.^v|Mutables
(= References)

.4+^.^|Identities
^| Atoms      ^| clojure.lang.Atom

^| Refs       ^| clojure.lang.Ref

^| Agents     ^| clojure.lang.Agent

^| Vars       ^| clojure.lang.Var

|===


:leveloffset: 1

include::sub/numbers.adoc[ ]

:leveloffset: 0


== 문자열(Strings)

클로저에서 문자열은 자기 자신으로 평가되는 값(value)으로, 쌍따옴표(`"`)로 둘러싸 표현한다.

[source]
....
"Welcome to Clojure!"          ;=> "Welcome to Clojure!"

(type "functional language")   ;=> java.lang.String
....

자바의 `java.lang.String` 클래스를 그대로 이용하므로, `String` 클래스의 메소드도 이용할 수
있다.

[source]
....
(.toUpperCase "modern lisp")   ;=> "MODERN LISP"
....

여러 줄의 입력도 가능하다.

[source]
....
"multiline strings
are allowed too."
;=> "multiline strings\nare allowed too."
....

`str` 함수는 주어진 인수들을 문자열로 변환한 후, 공백 없이 연결된 문자열을 반환한다. 단,
``nil``은 빈 문자열(`""`)로 변환된다.

[source]
....
(str)      ;=> ""
(str nil)  ;=> ""

(str 1)          ;=> "1"
(str 1 2 nil 3)  ;=> "123"

(str [1 2 3])    ;=> "[1 2 3]"

(str 1 'symbol :keyword)   ;=> "1symbol:keyword"
(str "Hello, " "World!")   ;=> "Hello, World!"
....

`format` 함수는 `java.lang.String.format` 함수를 그대로 이용한다. 자세한 포맷 서식은
`java.util.Formatter`
http://docs.oracle.com/javase/1.5.0/docs/api/java/util/Formatter.html[관련 문서]를
참조하도록 한다.

[source]
....
(format "Hello there, %s" "Bob")
;=> "Hello there, Bob"

(format "%5d" 3)
;=> "    3"

(format "Pad with leading zeros %07d" 5432)
;=> "Pad with leading zeros 0005432"

(format "Left justified :%-7d:" 5432)
;=> "Left justified :5432   :"
....


`subs` 함수는 주어진 문자열의 '시작 index(포함)'에서 '종료 index(불포함)'까지의 부분
문자열(substring)을 반환한다. index는 0부터 시작하고, '종료 index'가 주어지지 않으면,
문자열의 마지막까지 반환한다.

[source]
....
(subs "Clojure" 1 3)   ;=> "lo"
(subs "Clojure" 1)     ;=> "lojure"
....

문자열 처리 함수는 `clojure.string` 이름 공간에 별도로 더 많이 준비되어 있다.
