= Funcions and Functional Programming
:source-language: clojure
:source-highlighter: coderay
:sectnums:
:imagesdir: ../img
:linkcss:
:stylesdir: ../
:stylesheet: my-asciidoctor.css

== 함수형 언어란 무엇인가?

다음의 조건 네 가지를 충족시키면, 그 함수는 일급 함수(fisrt-class function)라고 부르고,
일급 함수를 지원하는 언어는 '전통적인 의미'에서의 함수형 언어라고 부를 수 있다.

. 함수 객체를 변수에 대입할 수 있다.
+
[source]
....
(def double (fn [a] (* 2 a)))   ; <1>

(double 10)    ; => 20

(def double2 double)

(double2 10)   ; => 20
....
<1> 특수 형식(special form) ``fn``을 이용해 먼저 함수 객체를 만든 후, 이 객체를
    ``double``이라는 심볼에 바인딩한다.

. 함수 객체를 함수의 인수로 전달할 수 있다.
+
[source]
....
(defn calc [op a b]
  (op a b))

(calc + 10 20)   ; => 30   ; <1>
(calc * 10 20)   ; => 200
....
<1> 함수 객체 ``+``를 `calc` 함수의 첫 번째 인수로 넘긴다.

. 함수 객체를 함수의 반환값으로 반환할 수 있다.
+
[source]
....
(defn operator [op]
  (cond
    (= op :plus)  +   ; <1>
    (= op :minus) -))

((operator :plus) 10 20)    ; => 30
((operator :minus) 10 20)   ; => -10
....
<1> 함수 객체 ``+``를 함수의 반환값으로 반환한다.

. 함수 객체를 동적으로 생성할 수 있다.
+
[source]
....
(defn multiple [n]
  (fn [a]   ; <1>
    (* n a)))

(def double (multiple 2))
; => #<Var@4340684b: #object[user$multiple$fn__12286 0x26a894a2]>

(def triple (multiple 3))
; => #<Var@fc4d31e: #object[user$multiple$fn__12286 0x1a4b7c5d]>

(double 10)   ; => 20
(triple 10)   ; => 30
....
<1> 함수를 동적으로 생성해 반환한다. 특수 형식 ``fn``이 수행될 때마다 새로운 함수 객체가
    생성된다.

TIP: 특히 위의 두 번째와 세 번째 조건을 충족시키는 함수를 고차 함수(higher-order
     function)라고 부른다.

오늘날 대부분의 언어가 함수형 언어의 영향을 받아, 위의 네 가지 조건을 모두 지원하거나
일부를 지원하고 있다. 그래서 루비나 파이썬, 심지어는 자바스크립트 언어마저도 위의 조건들을
모두 충족하고 있다. 그렇다면 이 세상은 이미 함수형 언어가 지배하고 있는 것일까? 함수형
언어를 어떻게 정의하느냐에 따라 의견이 달라질 수 있겠지만, 클로저 언어의 입장에서는 그렇게
보지 않는다. '현대적인 의미'에서, 즉 진정한 의미에서의 함수형 언어는 위의 네 가지 조건에
한 가지 조건을 더 만족시켜야 하는데, 그것은 바로 클로저나 해스켈처럼 불변형(immutable)
자료 구조를 기본적으로 지원해야 한다는 것이다.











